image:
  repository: velero/velero
  tag: v1.12.2

initContainers:
  # - name: velero-plugin-for-csi
  #   image: velero/velero-plugin-for-csi:v0.6.0
  #   imagePullPolicy: IfNotPresent
  #   volumeMounts:
  #     - mountPath: /target
  #       name: plugins
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.8.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

kubectl:
  image:
    repository: docker.io/bitnami/kubectl
    tag: 1.27.1

deployNodeAgent: true

configuration:
  backupStorageLocation: []
  volumeSnapshotLocation: []
  defaultVolumesToFsBackup: false
  uploaderType: kopia

nodeAgent:
  privileged: true
