apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-enterprise
spec:
  endpoints:
    - interval: 15s
      port: prometheus
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      redis.io/service: prom-metrics
